// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--rc3
// source: event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ======= Запросы =======
type AddChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	UserChatId    int32                  `protobuf:"varint,2,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChatRequest) Reset() {
	*x = AddChatRequest{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChatRequest) ProtoMessage() {}

func (x *AddChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChatRequest.ProtoReflect.Descriptor instead.
func (*AddChatRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *AddChatRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddChatRequest) GetUserChatId() int32 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

type UserChatIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserChatId    int32                  `protobuf:"varint,1,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserChatIDRequest) Reset() {
	*x = UserChatIDRequest{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChatIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatIDRequest) ProtoMessage() {}

func (x *UserChatIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatIDRequest.ProtoReflect.Descriptor instead.
func (*UserChatIDRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *UserChatIDRequest) GetUserChatId() int32 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

type FilteredCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserChatId    int32                  `protobuf:"varint,1,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	TimeFilter    string                 `protobuf:"bytes,2,opt,name=time_filter,json=timeFilter,proto3" json:"time_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilteredCatalogRequest) Reset() {
	*x = FilteredCatalogRequest{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredCatalogRequest) ProtoMessage() {}

func (x *FilteredCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredCatalogRequest.ProtoReflect.Descriptor instead.
func (*FilteredCatalogRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *FilteredCatalogRequest) GetUserChatId() int32 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

func (x *FilteredCatalogRequest) GetTimeFilter() string {
	if x != nil {
		return x.TimeFilter
	}
	return ""
}

type CategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserChatId    int32                  `protobuf:"varint,1,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryRequest) Reset() {
	*x = CategoryRequest{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryRequest) ProtoMessage() {}

func (x *CategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryRequest.ProtoReflect.Descriptor instead.
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryRequest) GetUserChatId() int32 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

func (x *CategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type FilteredCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserChatId    int32                  `protobuf:"varint,1,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	TimeFilter    string                 `protobuf:"bytes,3,opt,name=time_filter,json=timeFilter,proto3" json:"time_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilteredCategoryRequest) Reset() {
	*x = FilteredCategoryRequest{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredCategoryRequest) ProtoMessage() {}

func (x *FilteredCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredCategoryRequest.ProtoReflect.Descriptor instead.
func (*FilteredCategoryRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *FilteredCategoryRequest) GetUserChatId() int32 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

func (x *FilteredCategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FilteredCategoryRequest) GetTimeFilter() string {
	if x != nil {
		return x.TimeFilter
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatUsername  string                 `protobuf:"bytes,1,opt,name=chat_username,json=chatUsername,proto3" json:"chat_username,omitempty"`
	UserChatId    int32                  `protobuf:"varint,2,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *ChatRequest) GetChatUsername() string {
	if x != nil {
		return x.ChatUsername
	}
	return ""
}

func (x *ChatRequest) GetUserChatId() int32 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

type FilteredChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatUsername  string                 `protobuf:"bytes,1,opt,name=chat_username,json=chatUsername,proto3" json:"chat_username,omitempty"`
	UserChatId    int32                  `protobuf:"varint,2,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	TimeFilter    string                 `protobuf:"bytes,3,opt,name=time_filter,json=timeFilter,proto3" json:"time_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilteredChatRequest) Reset() {
	*x = FilteredChatRequest{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredChatRequest) ProtoMessage() {}

func (x *FilteredChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredChatRequest.ProtoReflect.Descriptor instead.
func (*FilteredChatRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *FilteredChatRequest) GetChatUsername() string {
	if x != nil {
		return x.ChatUsername
	}
	return ""
}

func (x *FilteredChatRequest) GetUserChatId() int32 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

func (x *FilteredChatRequest) GetTimeFilter() string {
	if x != nil {
		return x.TimeFilter
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

type CatalogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalogs      []*Catalog             `protobuf:"bytes,1,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogList) Reset() {
	*x = CatalogList{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogList) ProtoMessage() {}

func (x *CatalogList) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogList.ProtoReflect.Descriptor instead.
func (*CatalogList) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *CatalogList) GetCatalogs() []*Catalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

type FilteredCatalogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalogs      []*Catalog             `protobuf:"bytes,1,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilteredCatalogList) Reset() {
	*x = FilteredCatalogList{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredCatalogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredCatalogList) ProtoMessage() {}

func (x *FilteredCatalogList) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredCatalogList.ProtoReflect.Descriptor instead.
func (*FilteredCatalogList) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *FilteredCatalogList) GetCatalogs() []*Catalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

type ModeCatalogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalogs      []*Catalog             `protobuf:"bytes,1,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeCatalogList) Reset() {
	*x = ModeCatalogList{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeCatalogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeCatalogList) ProtoMessage() {}

func (x *ModeCatalogList) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeCatalogList.ProtoReflect.Descriptor instead.
func (*ModeCatalogList) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *ModeCatalogList) GetCatalogs() []*Catalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

type Catalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Channels      []*Channel             `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *Catalog) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Catalog) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *Channel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Channel) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	MessageLink   string                 `protobuf:"bytes,4,opt,name=message_link,json=messageLink,proto3" json:"message_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Event) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Event) GetMessageLink() string {
	if x != nil {
		return x.MessageLink
	}
	return ""
}

type EventCategoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCategoryList) Reset() {
	*x = EventCategoryList{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCategoryList) ProtoMessage() {}

func (x *EventCategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCategoryList.ProtoReflect.Descriptor instead.
func (*EventCategoryList) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *EventCategoryList) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventList) Reset() {
	*x = EventList{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventList) ProtoMessage() {}

func (x *EventList) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventList.ProtoReflect.Descriptor instead.
func (*EventList) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *EventList) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoriesResponse) Reset() {
	*x = CategoriesResponse{}
	mi := &file_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesResponse) ProtoMessage() {}

func (x *CategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesResponse.ProtoReflect.Descriptor instead.
func (*CategoriesResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{16}
}

func (x *CategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ChatList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatList) Reset() {
	*x = ChatList{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatList) ProtoMessage() {}

func (x *ChatList) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatList.ProtoReflect.Descriptor instead.
func (*ChatList) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{17}
}

func (x *ChatList) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{18}
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chat) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05proto\"N\n" +
	"\x0eAddChatRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12 \n" +
	"\fuser_chat_id\x18\x02 \x01(\x05R\n" +
	"userChatId\"5\n" +
	"\x11UserChatIDRequest\x12 \n" +
	"\fuser_chat_id\x18\x01 \x01(\x05R\n" +
	"userChatId\"[\n" +
	"\x16FilteredCatalogRequest\x12 \n" +
	"\fuser_chat_id\x18\x01 \x01(\x05R\n" +
	"userChatId\x12\x1f\n" +
	"\vtime_filter\x18\x02 \x01(\tR\n" +
	"timeFilter\"O\n" +
	"\x0fCategoryRequest\x12 \n" +
	"\fuser_chat_id\x18\x01 \x01(\x05R\n" +
	"userChatId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"x\n" +
	"\x17FilteredCategoryRequest\x12 \n" +
	"\fuser_chat_id\x18\x01 \x01(\x05R\n" +
	"userChatId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1f\n" +
	"\vtime_filter\x18\x03 \x01(\tR\n" +
	"timeFilter\"T\n" +
	"\vChatRequest\x12#\n" +
	"\rchat_username\x18\x01 \x01(\tR\fchatUsername\x12 \n" +
	"\fuser_chat_id\x18\x02 \x01(\x05R\n" +
	"userChatId\"}\n" +
	"\x13FilteredChatRequest\x12#\n" +
	"\rchat_username\x18\x01 \x01(\tR\fchatUsername\x12 \n" +
	"\fuser_chat_id\x18\x02 \x01(\x05R\n" +
	"userChatId\x12\x1f\n" +
	"\vtime_filter\x18\x03 \x01(\tR\n" +
	"timeFilter\"\a\n" +
	"\x05Empty\"9\n" +
	"\vCatalogList\x12*\n" +
	"\bcatalogs\x18\x01 \x03(\v2\x0e.proto.CatalogR\bcatalogs\"A\n" +
	"\x13FilteredCatalogList\x12*\n" +
	"\bcatalogs\x18\x01 \x03(\v2\x0e.proto.CatalogR\bcatalogs\"=\n" +
	"\x0fModeCatalogList\x12*\n" +
	"\bcatalogs\x18\x01 \x03(\v2\x0e.proto.CatalogR\bcatalogs\"Q\n" +
	"\aCatalog\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12*\n" +
	"\bchannels\x18\x02 \x03(\v2\x0e.proto.ChannelR\bchannels\"K\n" +
	"\aChannel\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12$\n" +
	"\x06events\x18\x02 \x03(\v2\f.proto.EventR\x06events\"q\n" +
	"\x05Event\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12!\n" +
	"\fmessage_link\x18\x04 \x01(\tR\vmessageLink\"9\n" +
	"\x11EventCategoryList\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.proto.EventR\x06events\"1\n" +
	"\tEventList\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.proto.EventR\x06events\"4\n" +
	"\x12CategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"-\n" +
	"\bChatList\x12!\n" +
	"\x05chats\x18\x01 \x03(\v2\v.proto.ChatR\x05chats\"6\n" +
	"\x04Chat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory2\xac\x05\n" +
	"\fEventService\x12.\n" +
	"\aAddChat\x12\x15.proto.AddChatRequest\x1a\f.proto.Empty\x12:\n" +
	"\n" +
	"GetCatalog\x12\x18.proto.UserChatIDRequest\x1a\x12.proto.CatalogList\x12O\n" +
	"\x12GetFilteredCatalog\x12\x1d.proto.FilteredCatalogRequest\x1a\x1a.proto.FilteredCatalogList\x12B\n" +
	"\x0eGetModeCatalog\x12\x18.proto.UserChatIDRequest\x1a\x16.proto.ModeCatalogList\x12G\n" +
	"\x13GetEventsByCategory\x12\x16.proto.CategoryRequest\x1a\x18.proto.EventCategoryList\x12W\n" +
	"\x1bGetFilteredEventsByCategory\x12\x1e.proto.FilteredCategoryRequest\x1a\x18.proto.EventCategoryList\x125\n" +
	"\rGetChatEvents\x12\x12.proto.ChatRequest\x1a\x10.proto.EventList\x12E\n" +
	"\x15GetFilteredChatEvents\x12\x1a.proto.FilteredChatRequest\x1a\x10.proto.EventList\x12D\n" +
	"\rGetCategories\x12\x18.proto.UserChatIDRequest\x1a\x19.proto.CategoriesResponse\x125\n" +
	"\bGetChats\x12\x18.proto.UserChatIDRequest\x1a\x0f.proto.ChatListB\x13Z\x11event/proto;protob\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_event_proto_goTypes = []any{
	(*AddChatRequest)(nil),          // 0: proto.AddChatRequest
	(*UserChatIDRequest)(nil),       // 1: proto.UserChatIDRequest
	(*FilteredCatalogRequest)(nil),  // 2: proto.FilteredCatalogRequest
	(*CategoryRequest)(nil),         // 3: proto.CategoryRequest
	(*FilteredCategoryRequest)(nil), // 4: proto.FilteredCategoryRequest
	(*ChatRequest)(nil),             // 5: proto.ChatRequest
	(*FilteredChatRequest)(nil),     // 6: proto.FilteredChatRequest
	(*Empty)(nil),                   // 7: proto.Empty
	(*CatalogList)(nil),             // 8: proto.CatalogList
	(*FilteredCatalogList)(nil),     // 9: proto.FilteredCatalogList
	(*ModeCatalogList)(nil),         // 10: proto.ModeCatalogList
	(*Catalog)(nil),                 // 11: proto.Catalog
	(*Channel)(nil),                 // 12: proto.Channel
	(*Event)(nil),                   // 13: proto.Event
	(*EventCategoryList)(nil),       // 14: proto.EventCategoryList
	(*EventList)(nil),               // 15: proto.EventList
	(*CategoriesResponse)(nil),      // 16: proto.CategoriesResponse
	(*ChatList)(nil),                // 17: proto.ChatList
	(*Chat)(nil),                    // 18: proto.Chat
}
var file_event_proto_depIdxs = []int32{
	11, // 0: proto.CatalogList.catalogs:type_name -> proto.Catalog
	11, // 1: proto.FilteredCatalogList.catalogs:type_name -> proto.Catalog
	11, // 2: proto.ModeCatalogList.catalogs:type_name -> proto.Catalog
	12, // 3: proto.Catalog.channels:type_name -> proto.Channel
	13, // 4: proto.Channel.events:type_name -> proto.Event
	13, // 5: proto.EventCategoryList.events:type_name -> proto.Event
	13, // 6: proto.EventList.events:type_name -> proto.Event
	18, // 7: proto.ChatList.chats:type_name -> proto.Chat
	0,  // 8: proto.EventService.AddChat:input_type -> proto.AddChatRequest
	1,  // 9: proto.EventService.GetCatalog:input_type -> proto.UserChatIDRequest
	2,  // 10: proto.EventService.GetFilteredCatalog:input_type -> proto.FilteredCatalogRequest
	1,  // 11: proto.EventService.GetModeCatalog:input_type -> proto.UserChatIDRequest
	3,  // 12: proto.EventService.GetEventsByCategory:input_type -> proto.CategoryRequest
	4,  // 13: proto.EventService.GetFilteredEventsByCategory:input_type -> proto.FilteredCategoryRequest
	5,  // 14: proto.EventService.GetChatEvents:input_type -> proto.ChatRequest
	6,  // 15: proto.EventService.GetFilteredChatEvents:input_type -> proto.FilteredChatRequest
	1,  // 16: proto.EventService.GetCategories:input_type -> proto.UserChatIDRequest
	1,  // 17: proto.EventService.GetChats:input_type -> proto.UserChatIDRequest
	7,  // 18: proto.EventService.AddChat:output_type -> proto.Empty
	8,  // 19: proto.EventService.GetCatalog:output_type -> proto.CatalogList
	9,  // 20: proto.EventService.GetFilteredCatalog:output_type -> proto.FilteredCatalogList
	10, // 21: proto.EventService.GetModeCatalog:output_type -> proto.ModeCatalogList
	14, // 22: proto.EventService.GetEventsByCategory:output_type -> proto.EventCategoryList
	14, // 23: proto.EventService.GetFilteredEventsByCategory:output_type -> proto.EventCategoryList
	15, // 24: proto.EventService.GetChatEvents:output_type -> proto.EventList
	15, // 25: proto.EventService.GetFilteredChatEvents:output_type -> proto.EventList
	16, // 26: proto.EventService.GetCategories:output_type -> proto.CategoriesResponse
	17, // 27: proto.EventService.GetChats:output_type -> proto.ChatList
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
