// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc3
// source: event.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_AddChat_FullMethodName                     = "/proto.EventService/AddChat"
	EventService_GetCatalog_FullMethodName                  = "/proto.EventService/GetCatalog"
	EventService_GetFilteredCatalog_FullMethodName          = "/proto.EventService/GetFilteredCatalog"
	EventService_GetModeCatalog_FullMethodName              = "/proto.EventService/GetModeCatalog"
	EventService_GetEventsByCategory_FullMethodName         = "/proto.EventService/GetEventsByCategory"
	EventService_GetFilteredEventsByCategory_FullMethodName = "/proto.EventService/GetFilteredEventsByCategory"
	EventService_GetChatEvents_FullMethodName               = "/proto.EventService/GetChatEvents"
	EventService_GetFilteredChatEvents_FullMethodName       = "/proto.EventService/GetFilteredChatEvents"
	EventService_GetCategories_FullMethodName               = "/proto.EventService/GetCategories"
	EventService_GetChats_FullMethodName                    = "/proto.EventService/GetChats"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	AddChat(ctx context.Context, in *AddChatRequest, opts ...grpc.CallOption) (*Empty, error)
	GetCatalog(ctx context.Context, in *UserChatIDRequest, opts ...grpc.CallOption) (*CatalogList, error)
	GetFilteredCatalog(ctx context.Context, in *FilteredCatalogRequest, opts ...grpc.CallOption) (*FilteredCatalogList, error)
	GetModeCatalog(ctx context.Context, in *UserChatIDRequest, opts ...grpc.CallOption) (*ModeCatalogList, error)
	GetEventsByCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*EventCategoryList, error)
	GetFilteredEventsByCategory(ctx context.Context, in *FilteredCategoryRequest, opts ...grpc.CallOption) (*EventCategoryList, error)
	GetChatEvents(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*EventList, error)
	GetFilteredChatEvents(ctx context.Context, in *FilteredChatRequest, opts ...grpc.CallOption) (*EventList, error)
	GetCategories(ctx context.Context, in *UserChatIDRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
	GetChats(ctx context.Context, in *UserChatIDRequest, opts ...grpc.CallOption) (*ChatList, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) AddChat(ctx context.Context, in *AddChatRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, EventService_AddChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetCatalog(ctx context.Context, in *UserChatIDRequest, opts ...grpc.CallOption) (*CatalogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogList)
	err := c.cc.Invoke(ctx, EventService_GetCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetFilteredCatalog(ctx context.Context, in *FilteredCatalogRequest, opts ...grpc.CallOption) (*FilteredCatalogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilteredCatalogList)
	err := c.cc.Invoke(ctx, EventService_GetFilteredCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetModeCatalog(ctx context.Context, in *UserChatIDRequest, opts ...grpc.CallOption) (*ModeCatalogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModeCatalogList)
	err := c.cc.Invoke(ctx, EventService_GetModeCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventsByCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*EventCategoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventCategoryList)
	err := c.cc.Invoke(ctx, EventService_GetEventsByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetFilteredEventsByCategory(ctx context.Context, in *FilteredCategoryRequest, opts ...grpc.CallOption) (*EventCategoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventCategoryList)
	err := c.cc.Invoke(ctx, EventService_GetFilteredEventsByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetChatEvents(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*EventList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventList)
	err := c.cc.Invoke(ctx, EventService_GetChatEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetFilteredChatEvents(ctx context.Context, in *FilteredChatRequest, opts ...grpc.CallOption) (*EventList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventList)
	err := c.cc.Invoke(ctx, EventService_GetFilteredChatEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetCategories(ctx context.Context, in *UserChatIDRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, EventService_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetChats(ctx context.Context, in *UserChatIDRequest, opts ...grpc.CallOption) (*ChatList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatList)
	err := c.cc.Invoke(ctx, EventService_GetChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	AddChat(context.Context, *AddChatRequest) (*Empty, error)
	GetCatalog(context.Context, *UserChatIDRequest) (*CatalogList, error)
	GetFilteredCatalog(context.Context, *FilteredCatalogRequest) (*FilteredCatalogList, error)
	GetModeCatalog(context.Context, *UserChatIDRequest) (*ModeCatalogList, error)
	GetEventsByCategory(context.Context, *CategoryRequest) (*EventCategoryList, error)
	GetFilteredEventsByCategory(context.Context, *FilteredCategoryRequest) (*EventCategoryList, error)
	GetChatEvents(context.Context, *ChatRequest) (*EventList, error)
	GetFilteredChatEvents(context.Context, *FilteredChatRequest) (*EventList, error)
	GetCategories(context.Context, *UserChatIDRequest) (*CategoriesResponse, error)
	GetChats(context.Context, *UserChatIDRequest) (*ChatList, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) AddChat(context.Context, *AddChatRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChat not implemented")
}
func (UnimplementedEventServiceServer) GetCatalog(context.Context, *UserChatIDRequest) (*CatalogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatalog not implemented")
}
func (UnimplementedEventServiceServer) GetFilteredCatalog(context.Context, *FilteredCatalogRequest) (*FilteredCatalogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilteredCatalog not implemented")
}
func (UnimplementedEventServiceServer) GetModeCatalog(context.Context, *UserChatIDRequest) (*ModeCatalogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModeCatalog not implemented")
}
func (UnimplementedEventServiceServer) GetEventsByCategory(context.Context, *CategoryRequest) (*EventCategoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventsByCategory not implemented")
}
func (UnimplementedEventServiceServer) GetFilteredEventsByCategory(context.Context, *FilteredCategoryRequest) (*EventCategoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilteredEventsByCategory not implemented")
}
func (UnimplementedEventServiceServer) GetChatEvents(context.Context, *ChatRequest) (*EventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatEvents not implemented")
}
func (UnimplementedEventServiceServer) GetFilteredChatEvents(context.Context, *FilteredChatRequest) (*EventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilteredChatEvents not implemented")
}
func (UnimplementedEventServiceServer) GetCategories(context.Context, *UserChatIDRequest) (*CategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedEventServiceServer) GetChats(context.Context, *UserChatIDRequest) (*ChatList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChats not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_AddChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddChat(ctx, req.(*AddChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChatIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetCatalog(ctx, req.(*UserChatIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetFilteredCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilteredCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetFilteredCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetFilteredCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetFilteredCatalog(ctx, req.(*FilteredCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetModeCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChatIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetModeCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetModeCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetModeCatalog(ctx, req.(*UserChatIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventsByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventsByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventsByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventsByCategory(ctx, req.(*CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetFilteredEventsByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilteredCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetFilteredEventsByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetFilteredEventsByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetFilteredEventsByCategory(ctx, req.(*FilteredCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetChatEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetChatEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetChatEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetChatEvents(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetFilteredChatEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilteredChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetFilteredChatEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetFilteredChatEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetFilteredChatEvents(ctx, req.(*FilteredChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChatIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetCategories(ctx, req.(*UserChatIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChatIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetChats(ctx, req.(*UserChatIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddChat",
			Handler:    _EventService_AddChat_Handler,
		},
		{
			MethodName: "GetCatalog",
			Handler:    _EventService_GetCatalog_Handler,
		},
		{
			MethodName: "GetFilteredCatalog",
			Handler:    _EventService_GetFilteredCatalog_Handler,
		},
		{
			MethodName: "GetModeCatalog",
			Handler:    _EventService_GetModeCatalog_Handler,
		},
		{
			MethodName: "GetEventsByCategory",
			Handler:    _EventService_GetEventsByCategory_Handler,
		},
		{
			MethodName: "GetFilteredEventsByCategory",
			Handler:    _EventService_GetFilteredEventsByCategory_Handler,
		},
		{
			MethodName: "GetChatEvents",
			Handler:    _EventService_GetChatEvents_Handler,
		},
		{
			MethodName: "GetFilteredChatEvents",
			Handler:    _EventService_GetFilteredChatEvents_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _EventService_GetCategories_Handler,
		},
		{
			MethodName: "GetChats",
			Handler:    _EventService_GetChats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
